# Generated by Django 3.2 on 2021-04-24 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='appp2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100)),
                ('Bias', models.CharField(max_length=50)),
                ('Age', models.IntegerField(max_length=200)),
                ('Country', models.TextField(max_length=50)),
            ],
        ),
    ]
